### ISSUE TITLE
Scroll-lock doesn't consider padding on container

### ISSUE THREAD

**Issue by mirayatech** [ttristan/ts-body-scroll-lock#4]
scroll-lock checks the height of all children and calculates their `height` from the container, but it doesn't calculate the padding.

**Comment by bonsaiapp** [comment]
Hi Miraya,
Thanks for the report. Would you be interested to create a fix for the issue? Happy to review your PR!

**Comment by ttristan** [comment]
Hi Miraya,
Thanks for the report. Would you be interested to create a fix for the issue? Happy to review your PR!
